topic_selection_task:
  description: >
    Analyze current trends in ML/AI/GenAI/MLOps/LLMOps to identify high-impact article topics.
    Consider recent research papers, industry developments, and emerging technologies.
    The goal is to select a topic that is both technically relevant and timely.
  expected_output: >
    A structured response containing:
    1. List of 3-5 potential topics, each with:
       - Topic title
       - Brief rationale highlighting novelty and impact
    2. Final recommendation with detailed justification for the selected topic

    The output should be formatted as a clear, readable text without any special markers.
  agent: chief_topic_strategist
